### ISSUE TITLE
Code not working

### ISSUE THREAD

**Issue by Imtiaz08** [ashaherb/Wiley-Downloader#4]
Hi, thank you so much for your work I am using the code to download a book that is divided into 34 chapters from wiley online library. At first I got some errors which I figured out by changing different things such as urllib2 to urllib3 and pyPDF3 etc however, I am still getting this error

Traceback (most recent call last):
File "c:\Users\IMTIAZ NABI\AppData\Local\Programs\Python\Python39\scraper.py", line 17, in
url = sys.argv[1]
IndexError: list index out of range

Kindly help me if you can I need this book for my research. Thank you once again

**Comment by ashaherb** [comment]
In order to run the script you need to run this in the Command line
`python scraper.py <book_url>`

If your use case can't run the command from the command line, You can remove this line
`url = sys.argv[1]`
and replace it with
`url = http://onlinelibrary.wiley.com/book/10.1002/9781118033104`

Where the url is your required book url
